name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'
          cache: true

      - name: Verify dependencies
        run: go mod verify

      - name: Run Tests
        run: make test || go test ./...

      - name: Build Binary
        run: make build || go build -o bin/books-api ./cmd/api/main.go

  docker:
    needs: test-and-build
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository }}:latest
          docker build -t $IMAGE_NAME .

      - name: Push Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository }}:latest
          docker push $IMAGE_NAME

